=== priyanshusharma44/HTML-CSS/schema/xmlANDschema/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="student">
  <xs:complexType>
   <xs:sequence>
      <xs:element name="id" type="xs:integer"/>
      <xs:element name="roll" type="xs:integer"/>
    <xs:element name="name">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fname" type="xs:string"/>
                <xs:element name="lname" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="address">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="city" type="xs:string"/>
                <xs:element name="state" type="xs:string"/>
                <xs:element name="pin" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== priyanshusharma44/HTML-CSS/schema/xmlANDschema/student.xml
<?xml version="1.0" encoding="UTF-8"?>

<student
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="schema.xsd">
    <id>123</id>
    <name>
        <fname>Ram</fname>
        <lname>Gurung</lname>
    </name>
    <roll>13</roll>
    <address>
        <city>Itahari</city>
        <state>province 1</state>
        <pin>2335</pin>
    </address>
</student>
