=== priyanshusharma44/HTML-CSS/Exam practics/xml,schema,dtd/bank.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="bank">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="customer">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:integer"/>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="address" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="account">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="accountId" type="xs:integer"/>
                        <xs:element name="branchId" type="xs:integer"/>
                        <xs:element name="customerId" type="xs:integer"/>
                        <xs:element name="accountType" type="xs:string"/>
                        <xs:element name="balance" type="xs:integer"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== priyanshusharma44/HTML-CSS/Exam practics/xml,schema,dtd/bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bank SYSTEM "bank.dtd">
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="bank.xsd">
    <customer>
        <id>123</id>
        <name>hari sharma</name>
        <address>itahari</address>
    </customer>
    <account>
        <accountId>2233</accountId>
        <branchId>9999</branchId>
        <customerId>123</customerId>
        <accountType>saving</accountType>
        <balance>2500000</balance>
    </account>
</bank>
